/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package aplikasi.penjualan.rumah;
import java.sql.Connection;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.util.logging.Logger;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import javax.swing.JDesktopPane;
import javax.swing.table.DefaultTableModel;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author CATURWARGA COMPUTER
 */
public class PaymentForm extends javax.swing.JInternalFrame {
    private DefaultTableModel model=null;
    private PreparedStatement stat;
    private ResultSet rs;
    Koneksi kon= new Koneksi();
    /**
     * Creates new form paymentForm
     */
    public PaymentForm() {
        initComponents();
        refreshtable();
    }
class rumah extends PaymentForm{
        int NomorPemesan,Tipe,Luas,Harga,JumlahCicilan,CicilanBulan,TotalHarga;
        String NamaPemesan,Area,TipePembayaran;
        
        public rumah(){
            NamaPemesan = orderNameTxt.getText();
            Area=areaCombobox.getSelectedItem().toString();
            Luas = Integer.parseInt( largeLandTxt.getText());
            Harga=Integer.parseInt( totalPriceTxt.getText());
            JumlahCicilan=Integer.parseInt( LamacicilanTxt.getText());
            CicilanBulan=Integer.parseInt( cicilanbulanTxt.getText());
            TotalHarga=Integer.parseInt( txtfinal.getText());
        }
    }

public void refreshtable(){
    model= new DefaultTableModel();
    model.addColumn("Nomor");
    model.addColumn("Nama Pemesan ");
    model.addColumn("Area ");
    model.addColumn("Type");
    model.addColumn("Luas");
    model.addColumn("Tipe Pembayaran");
    model.addColumn("Harga");
    model.addColumn("Jumlah Cicilan");
    model.addColumn("Cicilan Bulanan");
    model.addColumn("Total Harga");
    tablepay.setModel(model);
        try {         
            
            this.stat= kon.KoneksiDb().prepareStatement("select * from rumah");
            this.rs = this.stat.executeQuery(); 
            while (rs.next()) {                
                Object[] data ={
                    rs.getString("NomorPemesan"),
                    rs.getString("NamaPemesan"),
                    rs.getString("Area"),
                    rs.getString("Tipe"),
                    rs.getString("Luas"),
                    rs.getString("TipePembayaran"),
                    rs.getString("Harga"),
                    rs.getString("JumlahCicilan"),
                        rs.getString("CicilanBulan"),
                    rs.getString("TotalHarga")
                };
            model.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
       
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttongroup = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        orderNameTxt = new javax.swing.JTextField();
        priceLandTxt = new javax.swing.JTextField();
        areaCombobox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        t36radioButton = new javax.swing.JRadioButton();
        t45radioButton = new javax.swing.JRadioButton();
        t54radioButton = new javax.swing.JRadioButton();
        BuildingpriceTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        largeLandTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        availableTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        totalPriceTxt = new javax.swing.JTextField();
        DPTxt = new javax.swing.JTextField();
        LamacicilanTxt = new javax.swing.JTextField();
        cicilanbulanTxt = new javax.swing.JTextField();
        ppnTxt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        setujucbx = new javax.swing.JCheckBox();
        prosesbutton = new javax.swing.JButton();
        savebutton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        Rtunai = new javax.swing.JRadioButton();
        Rkredit = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        txtfinal = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablepay = new javax.swing.JTable();
        Refresh = new javax.swing.JButton();
        keutama1button = new javax.swing.JButton();
        chekbutton = new javax.swing.JButton();

        setTitle("FORM PENJUALAN");

        jLabel1.setText("Nama Pemesan");

        jLabel2.setText("Harga Tanah");

        jLabel3.setText("Area");

        areaCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---PILIH---", "BUGENVILE", "MELATI ", "FLAMBOYAN", " " }));
        areaCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaComboboxActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi/penjualan/rumah/rumah.jpeg"))); // NOI18N

        jLabel5.setText("Harga Bangunan");

        jLabel6.setText("Tipe bangunan");

        buttongroup.add(t36radioButton);
        t36radioButton.setText("tipe- 36");
        t36radioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t36radioButtonActionPerformed(evt);
            }
        });

        buttongroup.add(t45radioButton);
        t45radioButton.setText("tipe- 45");
        t45radioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t45radioButtonActionPerformed(evt);
            }
        });

        buttongroup.add(t54radioButton);
        t54radioButton.setText("tipe- 54");
        t54radioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t54radioButtonActionPerformed(evt);
            }
        });

        BuildingpriceTxt.setEditable(false);
        BuildingpriceTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel7.setText("Luas tanah asli");

        largeLandTxt.setEditable(false);
        largeLandTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel8.setText("Luas tanah tersedia");

        availableTxt.setEditable(false);
        availableTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel9.setText("harga");

        jLabel10.setText("DP");

        jLabel11.setText("Lama cicilan");

        jLabel12.setText("ppn(10%)");

        jLabel13.setText("cicilan/bulan");

        totalPriceTxt.setEditable(false);
        totalPriceTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        totalPriceTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalPriceTxtActionPerformed(evt);
            }
        });

        DPTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        LamacicilanTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        LamacicilanTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LamacicilanTxtActionPerformed(evt);
            }
        });

        cicilanbulanTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        cicilanbulanTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cicilanbulanTxtActionPerformed(evt);
            }
        });

        ppnTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ppnTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ppnTxtActionPerformed(evt);
            }
        });

        jLabel14.setText("Bulan");

        setujucbx.setText("Setuju");
        setujucbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setujucbxActionPerformed(evt);
            }
        });

        prosesbutton.setText("PROSES");
        prosesbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesbuttonActionPerformed(evt);
            }
        });

        savebutton.setText("SIMPAN");
        savebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebuttonActionPerformed(evt);
            }
        });

        deleteButton.setText("HAPUS");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(Rtunai);
        Rtunai.setText("tunai");
        Rtunai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RtunaiActionPerformed(evt);
            }
        });

        buttonGroup1.add(Rkredit);
        Rkredit.setText("Kredit");

        jLabel15.setText("Total");

        txtfinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfinalActionPerformed(evt);
            }
        });

        jLabel16.setText("Metode Pembayaran");

        tablepay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablepay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablepayMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablepay);

        Refresh.setText("Refresh ke Database");
        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });

        keutama1button.setText("ke menu utama");
        keutama1button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keutama1buttonActionPerformed(evt);
            }
        });

        chekbutton.setText("Cetak");
        chekbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chekbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Refresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(67, 67, 67)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(areaCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(orderNameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                    .addComponent(priceLandTxt))
                                .addGap(87, 87, 87))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(142, 142, 142)
                                        .addComponent(keutama1button)
                                        .addGap(67, 67, 67)
                                        .addComponent(chekbutton))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(69, 69, 69)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ppnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel16)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel10)
                                                        .addComponent(jLabel9))
                                                    .addComponent(jLabel13))
                                                .addGap(52, 52, 52))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addGap(100, 100, 100)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(Rtunai, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Rkredit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(DPTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                            .addComponent(totalPriceTxt)
                                            .addComponent(LamacicilanTxt)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(prosesbutton)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel15)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(cicilanbulanTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                                    .addComponent(txtfinal))))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel14)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                        .addComponent(setujucbx)
                                        .addGap(15, 15, 15))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(t45radioButton)
                                            .addComponent(t36radioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addComponent(t54radioButton)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(availableTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(largeLandTxt, javax.swing.GroupLayout.Alignment.LEADING))
                                                    .addComponent(BuildingpriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(123, 123, 123)
                                        .addComponent(savebutton)
                                        .addGap(48, 48, 48)
                                        .addComponent(deleteButton))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(BuildingpriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Refresh)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t36radioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(largeLandTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t45radioButton)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t54radioButton)
                            .addComponent(availableTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(orderNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(priceLandTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(areaCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(Rtunai)
                            .addComponent(Rkredit))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DPTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(LamacicilanTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ppnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(setujucbx)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cicilanbulanTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel15)
                                .addComponent(txtfinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(keutama1button, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chekbutton))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(deleteButton)
                                .addComponent(savebutton))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(prosesbutton)
                                .addGap(15, 15, 15)))))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/*class pesanan_rumah extends PaymentForm{
    int nomor_pemesan,luas_tanah,harga,lama_cicilan,cicilan_per_bulan;
    String nama_pemesan,area,tipe_rumah;
    public pesanan_rumah(){
        try {
            this.nomor_pemesan=Integer.parseInt(txNomorPemesanan.getText());
            this.nama_pemesan=orderNameTxt.getText();
            this.area=areaCombobox.getSelectedItem().toString();
           
        } catch (Exception e) {
        }
    }
}*/
    private void t36radioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t36radioButtonActionPerformed
      if(areaCombobox.getSelectedIndex() == 0) {
          JOptionPane.showMessageDialog(null,"Pilih area terlebih dahulu");
          buttongroup.clearSelection();
      }else{
          largeLandTxt.setText("90");
          availableTxt.setText("54");
          long landprice = Long.parseLong(priceLandTxt.getText()),
                  buildingprice = Long.parseLong(BuildingpriceTxt.getText()),
                  availableLand = Long.parseLong(availableTxt.getText()),
                  totalPrice;
          
           totalPrice = (availableLand * landprice)+ buildingprice;
           totalPriceTxt.setText("" + totalPrice);
           
           LamacicilanTxt.setText("");
           DPTxt.setText("");
           ppnTxt.setText("");
           cicilanbulanTxt.setText("");
      }
    }//GEN-LAST:event_t36radioButtonActionPerformed

    private void cicilanbulanTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cicilanbulanTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cicilanbulanTxtActionPerformed

    private void areaComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaComboboxActionPerformed
        switch(areaCombobox.getSelectedIndex()){
            case 0:
               priceLandTxt.setText("");
               BuildingpriceTxt.setText("");
               buttongroup.clearSelection();
               largeLandTxt.setText("");
               availableTxt.setText("");
               totalPriceTxt.setText("");
               DPTxt.setText("");
               LamacicilanTxt.setText("");
               cicilanbulanTxt.setText("");
               ppnTxt.setText("");
               setujucbx.setSelected(false);
   
                break;
               
            case 1:
               priceLandTxt.setText("500000");
               BuildingpriceTxt.setText("90000000");
               buttongroup.clearSelection();
               largeLandTxt.setText("");
               availableTxt.setText("");
               totalPriceTxt.setText("");
               DPTxt.setText("");
               LamacicilanTxt.setText("");
               cicilanbulanTxt.setText("");
               ppnTxt.setText("");
               setujucbx.setSelected(false);
               break;
               
             case 2:
               priceLandTxt.setText("600000");
               BuildingpriceTxt.setText("120000000");
               buttongroup.clearSelection();
               largeLandTxt.setText("");
               availableTxt.setText("");
               totalPriceTxt.setText("");
               DPTxt.setText("");
               LamacicilanTxt.setText("");
               cicilanbulanTxt.setText("");
               ppnTxt.setText("");
               setujucbx.setSelected(false);
               break;
               
             default:
               priceLandTxt.setText("700000");
               BuildingpriceTxt.setText("150000000");
               buttongroup.clearSelection();
               largeLandTxt.setText("");
               availableTxt.setText("");
               totalPriceTxt.setText("");
               DPTxt.setText("");
               LamacicilanTxt.setText("");
               cicilanbulanTxt.setText("");
               ppnTxt.setText("");
               setujucbx.setSelected(false);
               break;
        }
    }//GEN-LAST:event_areaComboboxActionPerformed

    private void t45radioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t45radioButtonActionPerformed
        if(areaCombobox.getSelectedIndex() == 0) {
          JOptionPane.showMessageDialog(null,"Pilih area terlebih dahulu");
          buttongroup.clearSelection();
      }else{
          largeLandTxt.setText("120");
          availableTxt.setText("75");
          long landprice = Long.parseLong(priceLandTxt.getText()),
                  buildingprice = Long.parseLong(BuildingpriceTxt.getText()),
                  availableLand = Long.parseLong(availableTxt.getText()),
                  totalPrice;
          
           totalPrice = (availableLand * landprice)+ buildingprice;
           totalPriceTxt.setText("" + totalPrice);
           
           LamacicilanTxt.setText("");
           DPTxt.setText("");
           ppnTxt.setText("");
           cicilanbulanTxt.setText("");
      }
    }//GEN-LAST:event_t45radioButtonActionPerformed

    private void t54radioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t54radioButtonActionPerformed
       if(areaCombobox.getSelectedIndex() == 0) {
          JOptionPane.showMessageDialog(null,"Pilih area terlebih dahulu");
          buttongroup.clearSelection();
      }else{
          largeLandTxt.setText("140");
          availableTxt.setText("86");
          long landprice = Long.parseLong(priceLandTxt.getText()),
                  buildingprice = Long.parseLong(BuildingpriceTxt.getText()),
                  availableLand = Long.parseLong(availableTxt.getText()),
                  totalPrice;
          
           totalPrice = (availableLand * landprice)+ buildingprice;
           totalPriceTxt.setText("" + totalPrice);
           
           LamacicilanTxt.setText("");
           DPTxt.setText("");
           ppnTxt.setText("");
           cicilanbulanTxt.setText("");
      }
    }//GEN-LAST:event_t54radioButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
       orderNameTxt.setText("");
       priceLandTxt.setText("");
       BuildingpriceTxt.setText("");
       largeLandTxt.setText("");
       availableTxt.setText("");
       totalPriceTxt.setText("");
       DPTxt.setText("");
       LamacicilanTxt.setText("");
       cicilanbulanTxt.setText("");
       ppnTxt.setText("");
       areaCombobox.setSelectedIndex(0);
       buttongroup.clearSelection();
       setujucbx.setSelected(false);
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void prosesbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesbuttonActionPerformed
                                        
    if (Rtunai.isSelected()) { // Cash
         
        if (totalPriceTxt.getText().isEmpty()) {
            
            JOptionPane.showMessageDialog(null, "Hitung total harga terlebih dahulu!");
            return;
        }
        long totalPrice = Long.parseLong(totalPriceTxt.getText());
        
        long ppn = (long) (totalPrice * 0.1); // PPN 10%
        long finalTotal = totalPrice + ppn;
        DPTxt.setText("0");
        LamacicilanTxt.setText("0");
        cicilanbulanTxt.setText("0");
        ppnTxt.setText("" + ppn); 
        txtfinal.setText("" + finalTotal); // Total + PPN
        JOptionPane.showMessageDialog(null, "Metode pembayaran: CASH\nPPN ditambahkan di total pembayaran.");
    } else if (Rkredit.isSelected()) { // Kredit
         //buttonGroup1.clearSelection(); 
        if (DPTxt.getText().isEmpty() || LamacicilanTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "DP dan Lama Cicilan harus diisi!");
        } else {
            long totalPrice = Long.parseLong(totalPriceTxt.getText());
            long dp = Long.parseLong(DPTxt.getText());
            int lamaCicilan = Integer.parseInt(LamacicilanTxt.getText());

            if (dp >= totalPrice) {
                JOptionPane.showMessageDialog(null, "DP harus lebih kecil dari total harga!");
                return;
            }

            long remaining = totalPrice - dp;
            long ppn = (long) (totalPrice * 0.1); // PPN 10%
            long cicilanPerBulan = remaining / lamaCicilan;
            
            ppnTxt.setText("" + ppn); // Tampilkan PPN
            cicilanbulanTxt.setText("" + cicilanPerBulan); // Cicilan/bulan
            txtfinal.setText("" + (totalPrice + ppn)); // Total + PPN
        }
    } else {
        buttonGroup1.clearSelection();
        JOptionPane.showMessageDialog(null, "Pilih metode pembayaran!");
    }
   

        //new DataForm().show();
        //this.dispose();
    }//GEN-LAST:event_prosesbuttonActionPerformed

    private void setujucbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setujucbxActionPerformed
        if(orderNameTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nama Pemesan Harus diisi");
            setujucbx.setSelected(false);
        }else if ( ppnTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "teken proses terlebih dahulu ");
            setujucbx.setSelected(false);
        }else if(setujucbx.isSelected() == true){
            JOptionPane.showMessageDialog(null, "pemesanan menyetujui");
            setujucbx.setSelected(true);
        }else{
            JOptionPane.showMessageDialog(null, "pesanan belum disetujui");
            setujucbx.setSelected(false);
        }
    }//GEN-LAST:event_setujucbxActionPerformed

    private void savebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebuttonActionPerformed
        if(setujucbx.isSelected() == false){
            JOptionPane.showMessageDialog(null,
                    "Klik centang checkbox untuk simpan data", "Error",
                     JOptionPane.ERROR_MESSAGE);
        }else{
           String typeHouse;
           if (t36radioButton.isSelected()){
              typeHouse = "Tipe 36";
         }else if (t45radioButton.isSelected()){
              typeHouse = "Tipe 45";                   
         }else{
              typeHouse = "Tipe 54";
         }
           
           String TypePay;
            if (Rtunai.isSelected()) {
                TypePay="tunai";
            } else {
                TypePay="Kredit";
            }
           
  
         try {
            rumah n = new rumah();
            this.stat= kon.KoneksiDb().prepareStatement("insert into rumah values(?,?,?,?,?,?,?,?,?,?)");                        
            stat.setInt(1, n.NomorPemesan);
            stat.setString(2, n.NamaPemesan);
            stat.setString(3, n.Area);
            stat.setString(4, typeHouse);
            stat.setInt(5, n.Luas);
            stat.setString(6, TypePay);
            stat.setInt(7, n.Harga);
            stat.setInt(8, n.JumlahCicilan);
            stat.setInt(9, n.CicilanBulan);
            stat.setInt(10, n.TotalHarga);
            stat.executeUpdate();          
         } catch (SQLException ex) {
             Logger.getLogger(PaymentForm.class.getName()).log(Level.SEVERE, null, ex);
         }
       orderNameTxt.setText("");
       priceLandTxt.setText("");
       BuildingpriceTxt.setText("");
       largeLandTxt.setText("");
       availableTxt.setText("");
       totalPriceTxt.setText("");
       DPTxt.setText("");
       LamacicilanTxt.setText("");
       cicilanbulanTxt.setText("");
       ppnTxt.setText("");
       areaCombobox.setSelectedIndex(0);
       buttongroup.clearSelection();
       txtfinal.setText("");
       setujucbx.setSelected(false);
         
          
       } 
    }//GEN-LAST:event_savebuttonActionPerformed

    private void totalPriceTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalPriceTxtActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_totalPriceTxtActionPerformed

    private void RtunaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RtunaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RtunaiActionPerformed

    private void LamacicilanTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LamacicilanTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LamacicilanTxtActionPerformed

    private void ppnTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ppnTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ppnTxtActionPerformed

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
        
// TODO add your handling code here:
        PaymentForm paymentForm = new PaymentForm();
              paymentForm.setVisible(true);
              this.getDesktopPane().add(paymentForm);
              this.dispose();
    }//GEN-LAST:event_RefreshActionPerformed

    private void keutama1buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keutama1buttonActionPerformed
       OptionMenu optionmenu = new OptionMenu();

// Menambahkan JInternalFrame ke dalam JDesktopPane
JDesktopPane desktopPane = this.getDesktopPane(); // Mengambil desktopPane dari parent
if (desktopPane != null) {
    desktopPane.add(optionmenu);
    optionmenu.setVisible(true); // Menampilkan JInternalFrame
} else {
    JOptionPane.showMessageDialog(this, "DesktopPane tidak ditemukan!");
}

// Menutup frame saat ini
this.dispose();
    }//GEN-LAST:event_keutama1buttonActionPerformed

    private void chekbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chekbuttonActionPerformed
        try {
    // Create a new document
    Document document = new Document();

    // Define the output file for the PDF
    PdfWriter.getInstance(document, new FileOutputStream("Transaction.pdf"));

    // Open the document
    document.open();

    // Fetch data from the fields (Replace these with your actual variables)
    String orderName = orderNameTxt.getText();
    String priceLand = priceLandTxt.getText();
    String buildingPrice = BuildingpriceTxt.getText();
    String largeLand = largeLandTxt.getText();
    String available = availableTxt.getText();
    String totalPrice = totalPriceTxt.getText();
       String typeHouse;
           if (t36radioButton.isSelected()){
              typeHouse = "Tipe 36";
         }else if (t45radioButton.isSelected()){
              typeHouse = "Tipe 45";                   
         }else{
              typeHouse = "Tipe 54";
         }
           
           String TypePay;
            if (Rtunai.isSelected()) {
                TypePay="tunai";
            } else {
                TypePay="Kredit";
            }
    String dp = DPTxt.getText();
    String installmentDuration = LamacicilanTxt.getText();
    String monthlyInstallment = cicilanbulanTxt.getText();
    String tax = ppnTxt.getText();
    String area = areaCombobox.getSelectedItem().toString();

    // Add content to the PDF
    document.add(new Paragraph("=== Real Estate Transaction Details ==="));
    document.add(new Paragraph("Order Name: " + orderName));
    document.add(new Paragraph("Price of Land: " + priceLand));
    document.add(new Paragraph("Building Price: " + buildingPrice));
    document.add(new Paragraph("Type House: " + typeHouse));
    document.add(new Paragraph("Land Size: " + largeLand));
    document.add(new Paragraph("Available: " + available));
    document.add(new Paragraph("Metode Pembayaran: " + TypePay));
    document.add(new Paragraph("Down Payment (DP): " + dp));
    document.add(new Paragraph("Installment Duration: " + installmentDuration));
    document.add(new Paragraph("Monthly Installment: " + monthlyInstallment));
    document.add(new Paragraph("PPN (Tax): " + tax));
    document.add(new Paragraph("Area: " + area));
    document.add(new Paragraph("Total Price: " + totalPrice));
    // Close the document
    document.close();

    System.out.println("PDF generated successfully!");

} catch (DocumentException | IOException ex) {
    Logger.getLogger(PaymentForm.class.getName()).log(Level.SEVERE, null, ex);
}


    }//GEN-LAST:event_chekbuttonActionPerformed

    private void txtfinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfinalActionPerformed

    private void tablepayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablepayMouseClicked
        // TODO add your handling code here:
        //txIdRental.setText(model.getValueAt(tbDataRental.getSelectedRow(),0).toString());
        //txNamaPelanggan.setText(model.getValueAt(tbDataRental.getSelectedRow(),3).toString());
        //txNamaAlat.setText(model.getValueAt(tbDataRental.getSelectedRow(),4).toString());
        //txHargaRental.setText(model.getValueAt(tbDataRental.getSelectedRow(),5).toString());
        //txStatus.setText(model.getValueAt(tbDataRental.getSelectedRow(),7).toString());
    }//GEN-LAST:event_tablepayMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BuildingpriceTxt;
    private javax.swing.JTextField DPTxt;
    private javax.swing.JTextField LamacicilanTxt;
    private javax.swing.JButton Refresh;
    private javax.swing.JRadioButton Rkredit;
    private javax.swing.JRadioButton Rtunai;
    private javax.swing.JComboBox<String> areaCombobox;
    private javax.swing.JTextField availableTxt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttongroup;
    private javax.swing.JButton chekbutton;
    private javax.swing.JTextField cicilanbulanTxt;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton keutama1button;
    private javax.swing.JTextField largeLandTxt;
    private javax.swing.JTextField orderNameTxt;
    private javax.swing.JTextField ppnTxt;
    private javax.swing.JTextField priceLandTxt;
    private javax.swing.JButton prosesbutton;
    private javax.swing.JButton savebutton;
    private javax.swing.JCheckBox setujucbx;
    private javax.swing.JRadioButton t36radioButton;
    private javax.swing.JRadioButton t45radioButton;
    private javax.swing.JRadioButton t54radioButton;
    private javax.swing.JTable tablepay;
    private javax.swing.JTextField totalPriceTxt;
    private javax.swing.JTextField txtfinal;
    // End of variables declaration//GEN-END:variables
}
